const data={
    Products:[
        {
            id: '1',
            name: 'Slim Fit',
            price:120,
            category:'Shirt',
            brand:'Nike',
            image: '/images/slim-fit.png',
            rating: 4.5,
            description:'Oke',
            numReviews: 10,
        },
        {
            id: '2',
            name: 'Slim Fit',
            price:100,
            category:'Shirt',
            rating: 4,
            brand:'Nike',
            image: '/images/slim-fit.png',
            description:'Oke',
            numReviews: 10,
        },
        {
            id: '3',
            name: 'Slim Fit',
            price:140,
            category:'Shirt',
            rating: 5,
            brand:'Nike',
            image: '/images/slim-fit.png',
            description:'Oke',
            numReviews: 10,
        },
        {
            id: '4',
            name: 'Slim Fit',
            price:200,
            category:'Shirt',
            rating: 4,
            brand:'Nike',
            image: '/images/slim-fit.png',
            description:'Oke',
            numReviews: 10,
        },
        {
            id: '5',
            name: 'Slim Fit',
            price:300,
            category:'Shirt',
            rating: 3,
            brand:'Nike',
            image: '/images/slim-fit.png',
            description:'Oke',
            numReviews: 10,
        },
    ]
}

export default data